# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Bash@3
  displayName: download latest release
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
       curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest \
      | grep  browser_download_url \
      | grep Linux-64bit.deb \
      | grep -v extended \
      | cut -d '"' -f 4 \
      | wget -i -
- task: Bash@3
  displayName: install from deb
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here     
      sudo dpkg -i hugo*_Linux-64bit.deb

- task: Bash@3
  displayName: build public folder
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here     
      hugo
- task: AzureFileCopy@3
  inputs:
    SourcePath: './public'
    azureSubscription: 'Visual Studio Professional(093f11e6-c3b7-42cf-aa06-77ce8e447b77)'
    Destination: 'AzureBlob'
    storage: 'jekyllstatic'
    ContainerName: '$web'
    AdditionalArgumentsForBlobCopy: '--recursive'
