# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      install hugo
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      hugo build

- task: AzureFileCopy@4
  inputs:
    SourcePath: './public'
    azureSubscription: 'Visual Studio Professional(093f11e6-c3b7-42cf-aa06-77ce8e447b77)'
    Destination: 'AzureBlob'
    storage: 'jekyllstatic'
    ContainerName: '$web'
    AdditionalArgumentsForBlobCopy: '--recursive'
